# Generated by Django 5.1.15 on 2026-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="código"
                    ),
                ),
                ("description", models.TextField(verbose_name="descripción")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Porcentaje"), ("fixed", "Monto fijo")],
                        max_length=20,
                        verbose_name="tipo de descuento",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor"
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="válido desde")),
                ("valid_until", models.DateTimeField(verbose_name="válido hasta")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="usos máximos"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="usos actuales"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
            ],
            options={
                "verbose_name": "Cupón",
                "verbose_name_plural": "Cupones",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DisplayMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="texto")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("promotion", "Promoción"),
                            ("birthday", "Cumpleaños"),
                            ("anniversary", "Aniversario"),
                            ("custom", "Personalizado"),
                            ("happy_hour", "Happy Hour"),
                        ],
                        default="promotion",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="válido desde")),
                ("valid_until", models.DateTimeField(verbose_name="válido hasta")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
            ],
            options={
                "verbose_name": "Mensaje en pantalla",
                "verbose_name_plural": "Mensajes en pantalla",
                "ordering": ("-created_at",),
            },
        ),
    ]
