# Generated by Django 5.1.15 on 2026-09-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Dueño de bar"),
                    ("superadmin", "Superadministrador"),
                    ("socio", "Socio"),
                ],
                default="owner",
                max_length=20,
                verbose_name="rol",
            ),
        ),
    ]
