# Generated by Django 5.1.15 on 2026-10-01 22:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userprofile_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="Comisión (%) del mercaderista sobre las ventas de sus bares.",
                max_digits=5,
                verbose_name="porcentaje de comisión",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Dueño de bar"),
                    ("superadmin", "Superadministrador"),
                    ("socio", "Socio"),
                    ("vendedor", "Mercaderista"),
                ],
                default="owner",
                max_length=20,
                verbose_name="rol",
            ),
        ),
    ]
