# Generated by Django 5.1.15 on 2026-09-08 16:57

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="nombre del bar"),
                ),
                (
                    "slug",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único en la URL y subdominio (solo minúsculas, números y guiones).",
                        max_length=63,
                        unique=True,
                        verbose_name="slug único",
                    ),
                ),
                (
                    "owner_email",
                    models.EmailField(max_length=254, verbose_name="email del dueño"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="dirección")),
                ("logo_url", models.URLField(blank=True, verbose_name="URL del logo")),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basic", "Básico"),
                            ("pro", "Pro"),
                            ("premium", "Premium"),
                        ],
                        default="basic",
                        max_length=20,
                        verbose_name="plan",
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("trialing", "En registro"),
                            ("active", "Activo"),
                            ("past_due", "Vencido"),
                            ("canceled", "Cancelado"),
                        ],
                        default="trialing",
                        max_length=20,
                        verbose_name="estado de suscripción",
                    ),
                ),
                (
                    "wompi_subscription_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID de suscripción en Wompi",
                    ),
                ),
                (
                    "wompi_card_token",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="token de tarjeta tokenizada (nunca datos de tarjeta)",
                    ),
                ),
                (
                    "next_billing_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="próxima fecha de facturación",
                    ),
                ),
                (
                    "max_tables",
                    models.PositiveIntegerField(
                        default=50, verbose_name="número máximo de mesas"
                    ),
                ),
                (
                    "requests_per_hour_limit",
                    models.PositiveIntegerField(
                        default=2, verbose_name="límite de peticiones por mesa por hora"
                    ),
                ),
                (
                    "crossfade_enabled",
                    models.BooleanField(
                        default=False, verbose_name="crossfade activado"
                    ),
                ),
                (
                    "autodj_enabled",
                    models.BooleanField(default=False, verbose_name="AutoDJ activado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
            ],
            options={
                "verbose_name": "Tenant (bar)",
                "verbose_name_plural": "Tenants (bares)",
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dominio",
                "verbose_name_plural": "Dominios",
            },
        ),
    ]
