# Generated by Django 5.1.15 on 2026-09-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="max_tables",
            field=models.PositiveIntegerField(
                default=8, verbose_name="número máximo de mesas"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="plan",
            field=models.CharField(
                choices=[("pro", "Pro"), ("premium", "Premium")],
                default="pro",
                max_length=20,
                verbose_name="plan",
            ),
        ),
    ]
