# Generated by Django 5.1.15 on 2026-09-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_tenant_max_tables_alter_tenant_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="genre",
            field=models.CharField(
                choices=[
                    ("vallenato", "Vallenato"),
                    ("reggaeton", "Reggaetón"),
                    ("salsa", "Salsa"),
                    ("cumbia", "Cumbia"),
                    ("ranchera", "Ranchera"),
                    ("pop_latino", "Pop latino"),
                    ("rock_espanol", "Rock en español"),
                    ("electronica", "Electrónica"),
                    ("crossover", "Variado"),
                ],
                default="crossover",
                help_text="Género del bar; el AutoDJ pide música acorde a este estilo.",
                max_length=20,
                verbose_name="género musical",
            ),
        ),
    ]
