# Generated by Django 5.1.15 on 2026-09-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_tenant_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("pro", "Pro"), ("premium", "Premium")],
                        max_length=20,
                        unique=True,
                        verbose_name="plan",
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="precio mensual (COP)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="vigente"),
                ),
            ],
            options={
                "verbose_name": "Precio de plan",
                "verbose_name_plural": "Precios de planes",
            },
        ),
    ]
