# Generated by Django 5.1.15 on 2026-09-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_planprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="planprice",
            name="extra_table_price",
            field=models.DecimalField(
                decimal_places=2,
                default=10000,
                max_digits=12,
                verbose_name="precio por mesa adicional (COP)",
            ),
        ),
        migrations.AddField(
            model_name="planprice",
            name="included_tables",
            field=models.PositiveIntegerField(
                default=8, verbose_name="mesas incluidas"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="included_tables",
            field=models.PositiveIntegerField(
                default=8,
                help_text="Mesas cubiertas por el precio base del plan. Las mesas por encima de este número se cobran aparte.",
                verbose_name="mesas incluidas en el plan",
            ),
        ),
        migrations.AlterField(
            model_name="planprice",
            name="plan",
            field=models.CharField(
                choices=[("pro", "Pro"), ("plus", "Plus"), ("premium", "Premium")],
                max_length=20,
                unique=True,
                verbose_name="plan",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="plan",
            field=models.CharField(
                choices=[("pro", "Pro"), ("plus", "Plus"), ("premium", "Premium")],
                default="pro",
                max_length=20,
                verbose_name="plan",
            ),
        ),
    ]
