# Generated by Django 5.1.15 on 2026-09-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_planprice_extra_table_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="autodj_enabled",
            field=models.BooleanField(default=True, verbose_name="AutoDJ activado"),
        ),
    ]
