# Generated by Django 5.1.15 on 2026-09-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_tenant_autodj_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="custom_genre",
            field=models.CharField(
                blank=True,
                help_text="Texto libre usado por el AutoDJ cuando el género es 'custom' (ej. 'baladas románticas').",
                max_length=100,
                verbose_name="género personalizado",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="genre",
            field=models.CharField(
                choices=[
                    ("vallenato", "Vallenato"),
                    ("reggaeton", "Reggaetón"),
                    ("salsa", "Salsa"),
                    ("cumbia", "Cumbia"),
                    ("ranchera", "Ranchera"),
                    ("pop_latino", "Pop latino"),
                    ("rock_espanol", "Rock en español"),
                    ("electronica", "Electrónica"),
                    ("crossover", "Variado"),
                    ("popular", "Música popular"),
                    ("banda", "Banda"),
                    ("nortena", "Norteña"),
                    ("bachata", "Bachata"),
                    ("merengue", "Merengue"),
                    ("tropical", "Tropical"),
                    ("champeta", "Champeta"),
                    ("corridos", "Corridos"),
                    ("custom", "Otro (personalizado)"),
                ],
                default="crossover",
                help_text="Género del bar; el AutoDJ pide música acorde a este estilo.",
                max_length=20,
                verbose_name="género musical",
            ),
        ),
    ]
