# Generated by Django 5.1.15 on 2026-10-01 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_tenant_custom_genre_alter_tenant_genre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Mercaderista que trajo/afilió este bar (vacío si fue directo).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brought_tenants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="vendedor",
            ),
        ),
    ]
