# Generated by Django 5.1.15 on 2026-09-08 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tables", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaylistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "youtube_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="ID de YouTube"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="título")),
                (
                    "artist",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="artista"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="duración en segundos"
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, verbose_name="URL de la miniatura"),
                ),
                (
                    "autodj_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activa, el AutoDJ puede elegirla automáticamente.",
                        verbose_name="aprobada para AutoDJ",
                    ),
                ),
                (
                    "play_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="veces reproducida"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
            ],
            options={
                "verbose_name": "Canción",
                "verbose_name_plural": "Canciones",
                "ordering": ("title",),
                "unique_together": {("youtube_id",)},
            },
        ),
        migrations.CreateModel(
            name="PlaylistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="favorita"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="templates",
                        to="music.playlistitem",
                        verbose_name="canciones",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de playlist",
                "verbose_name_plural": "Plantillas de playlist",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="QueueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_by",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="solicitada por"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobada"),
                            ("playing", "Reproduciendo"),
                            ("played", "Reproducida"),
                            ("skipped", "Saltada"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="posición en la cola"
                    ),
                ),
                (
                    "estimated_wait_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Suma de la duración de las canciones que van delante.",
                        verbose_name="tiempo estimado de espera (seg)",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="inicio de reproducción"
                    ),
                ),
                (
                    "played_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reproducida"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "playlist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_items",
                        to="music.playlistitem",
                        verbose_name="canción",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        help_text="Mesa que la pidió; vacío si la agregó el dueño o el AutoDJ.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queue_items",
                        to="tables.table",
                        verbose_name="mesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de cola",
                "verbose_name_plural": "Ítems de cola",
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="SongRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobada"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="solicitada"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="aprobada"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_requests",
                        to="users.userprofile",
                        verbose_name="aprobada por",
                    ),
                ),
                (
                    "playlist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="music.playlistitem",
                        verbose_name="canción",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_requests",
                        to="tables.table",
                        verbose_name="mesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Petición de canción",
                "verbose_name_plural": "Peticiones de canciones",
                "ordering": ("-requested_at",),
            },
        ),
    ]
