# Generated by Django 5.1.15 on 2026-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="número de mesa")),
                (
                    "qr_hash",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Identificador opaco usado en la URL del QR (no expone el tenant).",
                        max_length=64,
                        unique=True,
                        verbose_name="hash único del QR",
                    ),
                ),
                (
                    "qr_image_url",
                    models.URLField(blank=True, verbose_name="URL de la imagen QR"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
            ],
            options={
                "verbose_name": "Mesa",
                "verbose_name_plural": "Mesas",
                "unique_together": {("number",)},
            },
        ),
    ]
