[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://backend-production-8ade.up.railway.app/api/v1"
  VITE_DASHBOARD_URL = "https://flowmusic-dashboard.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
