# Generated by Django 5.1.15 on 2026-09-08 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wompi_transaction_id",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="ID de transacción en Wompi",
                    ),
                ),
                (
                    "wompi_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="referencia (order id)"
                    ),
                ),
                (
                    "amount_cents",
                    models.PositiveBigIntegerField(verbose_name="monto en centavos"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="COP", max_length=3, verbose_name="moneda"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobada"),
                            ("DECLINED", "Rechazada"),
                            ("VOIDED", "Anulada"),
                            ("ERROR", "Error"),
                        ],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="payload crudo del webhook",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="core.tenant",
                        verbose_name="tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción de pago",
                "verbose_name_plural": "Transacciones de pago",
                "ordering": ("-created_at",),
            },
        ),
    ]
