# Generated by Django 5.1.15 on 2026-10-01 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_expense_payment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="commission_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="% del vendedor vigente al momento del pago (snapshot).",
                max_digits=5,
                null=True,
                verbose_name="porcentaje de comisión aplicado",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Mercaderista vigente cuando se registró este pago (snapshot).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="vendedor",
            ),
        ),
        migrations.CreateModel(
            name="VendorPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        help_text="Primer día del mes liquidado.",
                        verbose_name="período",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="monto pagado (COP)",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de pago"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_vendor_payouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="marcado por",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_payouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación de vendedor",
                "verbose_name_plural": "Liquidaciones de vendedores",
                "ordering": ("-period",),
                "unique_together": {("vendor", "period")},
            },
        ),
    ]
