# Generated by Django 5.1.15 on 2026-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="fecha")),
                (
                    "total_requests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total de peticiones"
                    ),
                ),
                (
                    "approved_requests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="peticiones aprobadas"
                    ),
                ),
                (
                    "songs_played",
                    models.PositiveIntegerField(
                        default=0, verbose_name="canciones reproducidas"
                    ),
                ),
                (
                    "avg_wait_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tiempo promedio de espera (seg)"
                    ),
                ),
                (
                    "top_songs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="canciones más solicitadas",
                    ),
                ),
                (
                    "estimated_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ventas estimadas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
            ],
            options={
                "verbose_name": "Analítica de ventas",
                "verbose_name_plural": "Analíticas de ventas",
                "ordering": ("-date",),
                "unique_together": {("date",)},
            },
        ),
    ]
